M48
; DRILL file {KiCad (6.0.6)} date Fri Jul 22 23:00:58 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-22T23:00:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X78.021Y-48.17
X78.021Y-113.575
X221.531Y-48.17
X221.531Y-113.575
T0
M30
